approach_node:
  ros__parameters:
    
    img_width: 640
    img_height: 360
    
    
    target_x_offset: 370.0
    
   
    yaw_kp: 0.002           
    forward_speed: 0.1      
    
    
    stop_y_threshold: 280.0 
    align_threshold: 15.0   
    timeout_lost: 1.0       
