brickpick_vision:
  ros__parameters:
    
    model_path: "best.pt"  
    device: "cuda:0"            
    
    
    camera_topic: "camera/image_color"
    
   
    conf_threshold: 0.5
    iou_threshold: 0.45
    imgsz: 640
    
   
    publish_debug_image: true
